// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Friendship is the predicate function for friendship builders.
type Friendship func(*sql.Selector)

// FriendshipRequest is the predicate function for friendshiprequest builders.
type FriendshipRequest func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)
