version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.3
    ports:
      - 15432:5432
    volumes:
      - ./scripts/postgres-init-local.sh:/docker-entrypoint-initdb.d/init-local.sh
      - db_data:/var/lib/mysql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invy

  redis:
    # https://docs.upstash.com/redis/overall/rediscompatibility
    image: redis:6.2
    ports:
      - 16379:6379

volumes:
  db_data:
