// Code generated by ent, DO NOT EDIT.

package invitationuser

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the invitationuser type in the database.
	Label = "invitation_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInvitationID holds the string denoting the invitation_id field in the database.
	FieldInvitationID = "invitation_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeInvitation holds the string denoting the invitation edge name in mutations.
	EdgeInvitation = "invitation"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the invitationuser in the database.
	Table = "invitation_users"
	// InvitationTable is the table that holds the invitation relation/edge.
	InvitationTable = "invitation_users"
	// InvitationInverseTable is the table name for the Invitation entity.
	// It exists in this package in order to avoid circular dependency with the "invitation" package.
	InvitationInverseTable = "invitations"
	// InvitationColumn is the table column denoting the invitation relation/edge.
	InvitationColumn = "invitation_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invitation_users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for invitationuser fields.
var Columns = []string{
	FieldID,
	FieldInvitationID,
	FieldUserID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
