// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package query

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID          uuid.UUID
	AuthID      string
	Email       sql.NullString
	PhoneNumber sql.NullString
	Status      string
	CreatedAt   time.Time
}

type FriendGroup struct {
	ID         uuid.UUID
	Name       string
	TotalCount int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
}

type Friendship struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UserID       uuid.UUID
	FriendUserID uuid.UUID
}

type FriendshipRequest struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	FromUserID uuid.UUID
	ToUserID   uuid.UUID
}

type Invitation struct {
	ID         uuid.UUID
	Location   string
	Coordinate interface{}
	Comment    string
	StartsAt   time.Time
	ChatRoomID uuid.NullUUID
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
}

type InvitationAcceptance struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UserID       uuid.UUID
	InvitationID uuid.UUID
}

type InvitationAwaiting struct {
	ID        uuid.UUID
	StartsAt  time.Time
	EndsAt    time.Time
	Comment   string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type InvitationDenial struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UserID       uuid.UUID
	InvitationID uuid.UUID
}

type InvitationUser struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	InvitationID uuid.UUID
	UserID       uuid.UUID
}

type PushNotificationToken struct {
	ID        uuid.UUID
	DeviceID  string
	FcmToken  string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
	AccountID uuid.UUID
}

type UserBlock struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UserID      uuid.UUID
	BlockUserID uuid.UUID
}

type UserFriendGroup struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	FriendGroupID uuid.UUID
	UserID        uuid.UUID
}

type UserLocation struct {
	ID         uuid.UUID
	Coordinate interface{}
	UpdatedAt  time.Time
	UserID     uuid.UUID
}

type UserLocationHistory struct {
	ID         uuid.UUID
	Coordinate interface{}
	CreatedAt  time.Time
	UserID     uuid.UUID
}

type UserMute struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UserID     uuid.UUID
	MuteUserID uuid.UUID
}

type UserProfile struct {
	ID        uuid.UUID
	ScreenID  string
	Nickname  string
	AvatarUrl string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}
