targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/**
          clients:
            - graphql
            - graphql_flutter
          scalars:
            Time:
              type: DateTime
            UUID:
              type: String
            Cursor:
              type: String
            Upload:
              type: MultipartFile
              fromJsonFunctionName: fileFromJson
              toJsonFunctionName: fileToJson
              import: package:invy/graphql/scalars.dart
