targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scopes:
            - lib/**
          clients:
            - graphql
            - graphql_flutter
          scalars:
            Time:
              type: DateTime
            UUID:
              type: String
            Cursor:
              type: String
