// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k-yomo/invy/invy_api/ent/friendshiprequest"
	"github.com/k-yomo/invy/invy_api/ent/predicate"
)

// FriendshipRequestDelete is the builder for deleting a FriendshipRequest entity.
type FriendshipRequestDelete struct {
	config
	hooks    []Hook
	mutation *FriendshipRequestMutation
}

// Where appends a list predicates to the FriendshipRequestDelete builder.
func (frd *FriendshipRequestDelete) Where(ps ...predicate.FriendshipRequest) *FriendshipRequestDelete {
	frd.mutation.Where(ps...)
	return frd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (frd *FriendshipRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, FriendshipRequestMutation](ctx, frd.sqlExec, frd.mutation, frd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (frd *FriendshipRequestDelete) ExecX(ctx context.Context) int {
	n, err := frd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (frd *FriendshipRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(friendshiprequest.Table, sqlgraph.NewFieldSpec(friendshiprequest.FieldID, field.TypeUUID))
	if ps := frd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, frd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	frd.mutation.done = true
	return affected, err
}

// FriendshipRequestDeleteOne is the builder for deleting a single FriendshipRequest entity.
type FriendshipRequestDeleteOne struct {
	frd *FriendshipRequestDelete
}

// Where appends a list predicates to the FriendshipRequestDelete builder.
func (frdo *FriendshipRequestDeleteOne) Where(ps ...predicate.FriendshipRequest) *FriendshipRequestDeleteOne {
	frdo.frd.mutation.Where(ps...)
	return frdo
}

// Exec executes the deletion query.
func (frdo *FriendshipRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := frdo.frd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{friendshiprequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (frdo *FriendshipRequestDeleteOne) ExecX(ctx context.Context) {
	if err := frdo.Exec(ctx); err != nil {
		panic(err)
	}
}
