// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k-yomo/invy/invy_api/ent/invitationdenial"
	"github.com/k-yomo/invy/invy_api/ent/predicate"
)

// InvitationDenialDelete is the builder for deleting a InvitationDenial entity.
type InvitationDenialDelete struct {
	config
	hooks    []Hook
	mutation *InvitationDenialMutation
}

// Where appends a list predicates to the InvitationDenialDelete builder.
func (idd *InvitationDenialDelete) Where(ps ...predicate.InvitationDenial) *InvitationDenialDelete {
	idd.mutation.Where(ps...)
	return idd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (idd *InvitationDenialDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(idd.hooks) == 0 {
		affected, err = idd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InvitationDenialMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			idd.mutation = mutation
			affected, err = idd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(idd.hooks) - 1; i >= 0; i-- {
			if idd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = idd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, idd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (idd *InvitationDenialDelete) ExecX(ctx context.Context) int {
	n, err := idd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (idd *InvitationDenialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: invitationdenial.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: invitationdenial.FieldID,
			},
		},
	}
	if ps := idd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, idd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// InvitationDenialDeleteOne is the builder for deleting a single InvitationDenial entity.
type InvitationDenialDeleteOne struct {
	idd *InvitationDenialDelete
}

// Exec executes the deletion query.
func (iddo *InvitationDenialDeleteOne) Exec(ctx context.Context) error {
	n, err := iddo.idd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invitationdenial.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iddo *InvitationDenialDeleteOne) ExecX(ctx context.Context) {
	iddo.idd.ExecX(ctx)
}
