// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/k-yomo/invy/invy_api/ent/invitation"
	"github.com/k-yomo/invy/invy_api/ent/invitationdenial"
	"github.com/k-yomo/invy/invy_api/ent/user"
)

// InvitationDenial is the model entity for the InvitationDenial schema.
type InvitationDenial struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// InvitationID holds the value of the "invitation_id" field.
	InvitationID uuid.UUID `json:"invitation_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvitationDenialQuery when eager-loading is set.
	Edges InvitationDenialEdges `json:"edges"`
}

// InvitationDenialEdges holds the relations/edges for other nodes in the graph.
type InvitationDenialEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Invitation holds the value of the invitation edge.
	Invitation *Invitation `json:"invitation,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationDenialEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// InvitationOrErr returns the Invitation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationDenialEdges) InvitationOrErr() (*Invitation, error) {
	if e.loadedTypes[1] {
		if e.Invitation == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: invitation.Label}
		}
		return e.Invitation, nil
	}
	return nil, &NotLoadedError{edge: "invitation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvitationDenial) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitationdenial.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case invitationdenial.FieldID, invitationdenial.FieldUserID, invitationdenial.FieldInvitationID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type InvitationDenial", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvitationDenial fields.
func (id *InvitationDenial) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitationdenial.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				id.ID = *value
			}
		case invitationdenial.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				id.UserID = *value
			}
		case invitationdenial.FieldInvitationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field invitation_id", values[i])
			} else if value != nil {
				id.InvitationID = *value
			}
		case invitationdenial.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				id.CreatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the InvitationDenial entity.
func (id *InvitationDenial) QueryUser() *UserQuery {
	return (&InvitationDenialClient{config: id.config}).QueryUser(id)
}

// QueryInvitation queries the "invitation" edge of the InvitationDenial entity.
func (id *InvitationDenial) QueryInvitation() *InvitationQuery {
	return (&InvitationDenialClient{config: id.config}).QueryInvitation(id)
}

// Update returns a builder for updating this InvitationDenial.
// Note that you need to call InvitationDenial.Unwrap() before calling this method if this InvitationDenial
// was returned from a transaction, and the transaction was committed or rolled back.
func (id *InvitationDenial) Update() *InvitationDenialUpdateOne {
	return (&InvitationDenialClient{config: id.config}).UpdateOne(id)
}

// Unwrap unwraps the InvitationDenial entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (id *InvitationDenial) Unwrap() *InvitationDenial {
	_tx, ok := id.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvitationDenial is not a transactional entity")
	}
	id.config.driver = _tx.drv
	return id
}

// String implements the fmt.Stringer.
func (id *InvitationDenial) String() string {
	var builder strings.Builder
	builder.WriteString("InvitationDenial(")
	builder.WriteString(fmt.Sprintf("id=%v, ", id.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", id.UserID))
	builder.WriteString(", ")
	builder.WriteString("invitation_id=")
	builder.WriteString(fmt.Sprintf("%v", id.InvitationID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(id.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvitationDenials is a parsable slice of InvitationDenial.
type InvitationDenials []*InvitationDenial

func (id InvitationDenials) config(cfg config) {
	for _i := range id {
		id[_i].config = cfg
	}
}
