// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/k-yomo/invy/invy_api/ent/user"
	"github.com/k-yomo/invy/invy_api/ent/userblock"
)

// UserBlock is the model entity for the UserBlock schema.
type UserBlock struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// BlockUserID holds the value of the "block_user_id" field.
	BlockUserID uuid.UUID `json:"block_user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserBlockQuery when eager-loading is set.
	Edges        UserBlockEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserBlockEdges holds the relations/edges for other nodes in the graph.
type UserBlockEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// BlockUser holds the value of the block_user edge.
	BlockUser *User `json:"block_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBlockEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// BlockUserOrErr returns the BlockUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBlockEdges) BlockUserOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.BlockUser == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.BlockUser, nil
	}
	return nil, &NotLoadedError{edge: "block_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserBlock) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userblock.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case userblock.FieldID, userblock.FieldUserID, userblock.FieldBlockUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserBlock fields.
func (ub *UserBlock) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userblock.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ub.ID = *value
			}
		case userblock.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				ub.UserID = *value
			}
		case userblock.FieldBlockUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field block_user_id", values[i])
			} else if value != nil {
				ub.BlockUserID = *value
			}
		case userblock.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ub.CreatedAt = value.Time
			}
		default:
			ub.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserBlock.
// This includes values selected through modifiers, order, etc.
func (ub *UserBlock) Value(name string) (ent.Value, error) {
	return ub.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserBlock entity.
func (ub *UserBlock) QueryUser() *UserQuery {
	return NewUserBlockClient(ub.config).QueryUser(ub)
}

// QueryBlockUser queries the "block_user" edge of the UserBlock entity.
func (ub *UserBlock) QueryBlockUser() *UserQuery {
	return NewUserBlockClient(ub.config).QueryBlockUser(ub)
}

// Update returns a builder for updating this UserBlock.
// Note that you need to call UserBlock.Unwrap() before calling this method if this UserBlock
// was returned from a transaction, and the transaction was committed or rolled back.
func (ub *UserBlock) Update() *UserBlockUpdateOne {
	return NewUserBlockClient(ub.config).UpdateOne(ub)
}

// Unwrap unwraps the UserBlock entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ub *UserBlock) Unwrap() *UserBlock {
	_tx, ok := ub.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserBlock is not a transactional entity")
	}
	ub.config.driver = _tx.drv
	return ub
}

// String implements the fmt.Stringer.
func (ub *UserBlock) String() string {
	var builder strings.Builder
	builder.WriteString("UserBlock(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ub.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ub.UserID))
	builder.WriteString(", ")
	builder.WriteString("block_user_id=")
	builder.WriteString(fmt.Sprintf("%v", ub.BlockUserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ub.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserBlocks is a parsable slice of UserBlock.
type UserBlocks []*UserBlock
