name: Trigger App Deploy

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Deploy on codemagic can be triggered only by branch and can't use paths filter.
      # This workflow is a workaround to deploy app only when files under app directory change.
      - name: Push commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -f origin ${GITHUB_REF##*/}:app-main
