name: Invy API Workflow
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/invy-api.yml"
      - "invy_api/**"
      - "pkg/**"
  pull_request:
    paths:
      - ".github/workflows/invy-api.yml"
      - "invy_api/**"
      - "pkg/**"

permissions:
  contents: read
  id-token: write

env:
  TZ: "Asia/Tokyo"
  GAR_PROJECT: invy-${{ (github.ref_type == 'tag' || github.ref == 'refs/heads/main') && 'prod' || 'dev' }}

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore tools cache
        id: restore-tools-cache
        uses: actions/cache@v3
        with:
          key: tools-${{ hashFiles('tools/go.sum') }}
          path: |
            ./bin

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download modules
        if: steps.restore-tools-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install tools
        if: steps.restore-tools-cache.outputs.cache-hit != 'true'
        run: make setup-go

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: dependencies
    services:
      postgres:
        image: postgis/postgis:13-3.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: invy_test
        ports:
          - 15432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 5
    env:
      PGHOST: localhost
      PGPORT: 15432
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: invy_test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Restore tools cache
        uses: actions/cache@v3
        with:
          key: tools-${{ hashFiles('tools/go.sum') }}
          path: |
            ./bin

      - name: Setup postgis
        run: psql -c 'CREATE EXTENSION postgis'

      - name: Test
        run: make test-api

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Restore tools cache
        uses: actions/cache@v3
        with:
          key: tools-${{ hashFiles('tools/go.sum') }}
          path: |
            ./bin

      - name: Lint
        run: make lint-api

  docker-build-push:
    name: Docker build and push
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/936800855868/locations/global/workloadIdentityPools/github/providers/github-provider
          service_account: api-ci-prod@invy-prod.iam.gserviceaccount.com

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Push Docker Image to Prod GAR
        id: push-docker-image
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud --quiet auth configure-docker asia-northeast1-docker.pkg.dev
          COMMIT_REF_SHORT=$(git rev-parse --short=7 HEAD)
          if [ "${GITHUB_REF_NAME}" == "main" ]; then
            export VERSION=${GITHUB_REF_NAME}-$(date +%Y%m%d)-${COMMIT_REF_SHORT}
          elif [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
            PR_SHA=${{ github.event.pull_request.head.sha }}
            export VERSION=pr-${PR_NUMBER}-${PR_SHA:0:7}
          else
            export VERSION=commit-${GITHUB_SHA:0:7}
          fi
          make docker-push-api
          make add-latest-latest-tag-to-api
          echo "docker-image-version=${VERSION}" >> "$GITHUB_OUTPUT"
        env:
          DOCKER_BUILDKIT: 1
    outputs:
      docker-image-version: ${{ steps.push-docker-image.outputs.docker-image-version }}


  deploy-dev:
    name: Deploy Dev
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: invy-api-dev
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/434214998297/locations/global/workloadIdentityPools/github/providers/github-provider
          service_account: api-ci-dev@invy-dev.iam.gserviceaccount.com

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Dev
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud run deploy invy-api-dev --image=asia-northeast1-docker.pkg.dev/invy-prod/invy/invy-api:${VERSION} --project=invy-dev --region=asia-northeast1 --platform=managed
        env:
          VERSION: ${{needs.docker-build-push.outputs.docker-image-version}}

  deploy-prod:
    name: Deploy Prod
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: invy-api-prod
    steps:
     - uses: actions/checkout@v3
     - name: Authenticate Google Cloud
       uses: google-github-actions/auth@v1
       with:
         workload_identity_provider: projects/936800855868/locations/global/workloadIdentityPools/github/providers/github-provider
         service_account: api-ci-prod@invy-prod.iam.gserviceaccount.com

     - name: Setup Cloud SDK
       uses: google-github-actions/setup-gcloud@v1

     - name: Deploy Prod
       if: github.ref == 'refs/heads/main'
       run: |
         gcloud run deploy invy-api-prod --image=asia-northeast1-docker.pkg.dev/invy-prod/invy/invy-api:${VERSION} --project=invy-prod --region=asia-northeast1 --platform=managed
       env:
        VERSION: ${{needs.docker-build-push.outputs.docker-image-version}}
